name: Deploy
on:
  push:
    branches:
      - v2-dev
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Setup
      #   uses: actions/setup-node@v3
      # - uses: actions/checkout@v4
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 8
      #     run_install: |
      #       - recursive: true
      #         args: [--frozen-lockfile, --strict-peer-dependencies]
      #       - args: [--global, prettier, typescript]

      - name: Build
        run: |
          git submodule init
          git submodule update
          npm install -g pnpm
          pnpm i
          pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
